export interface GeminiImageResponse {
  url: string;
  base64?: string;
}

export async function generatePenDrawingImage(
  prompt: string,
  apiKey?: string
): Promise<string | null> {
  const geminiApiKey = apiKey || import.meta.env.VITE_GEMINI_API_KEY;

  if (!geminiApiKey) {
    console.warn('Gemini API key not configured');
    return null;
  }

  try {
    const enhancedPrompt = `Create a detailed pen drawing illustration in black and white line art style. ${prompt}. Style: hand-drawn pen sketch, clean lines, artistic, professional illustration suitable for an ebook.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${geminiApiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: enhancedPrompt
            }]
          }],
          generationConfig: {
            temperature: 0.4,
            topK: 32,
            topP: 1,
            maxOutputTokens: 4096,
          }
        }),
      }
    );

    if (!response.ok) {
      console.error('Gemini API error:', response.status, await response.text());
      return null;
    }

    const data = await response.json();

    if (data.candidates && data.candidates[0]?.content?.parts?.[0]?.inlineData) {
      const base64Data = data.candidates[0].content.parts[0].inlineData.data;
      const mimeType = data.candidates[0].content.parts[0].inlineData.mimeType;
      return `data:${mimeType};base64,${base64Data}`;
    }

    console.warn('No image generated by Gemini');
    return null;
  } catch (error) {
    console.error('Error generating image with Gemini:', error);
    return null;
  }
}

export async function getCoverImage(subject: string): Promise<string | null> {
  return generatePenDrawingImage(`Cover illustration for an ebook about ${subject}`);
}

export async function getChapterImages(
  chapters: Array<{title: string}>,
  subject: string
): Promise<(string | null)[]> {
  const images: (string | null)[] = [];

  for (const chapter of chapters) {
    const prompt = `Illustration for a chapter titled "${chapter.title}" in an ebook about ${subject}`;
    const image = await generatePenDrawingImage(prompt);
    images.push(image);
  }

  return images;
}
